version: '3'

services:

  backend:
    container_name: cess-advisor-backend
    restart: unless-stopped
    build:
      context: .
    volumes:
      - './logs:/app/logs'
    ports:
      - 3057:3000
