name: build-backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: cess-advisor-backend
          tags: latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
