name: deploy-backend

on:
  push:
    branches: [ "main" ]

steps:
  - uses: actions/checkout@v3
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v6
    name: Build & push Docker image
    with:
      image: cess-advisor-backend
      tags: latest
      registry: ghcr.io
      dockerfile: Dockerfile
      username: ${{ secrets.GHCR_USERNAME }}
      password: ${{ secrets.GHCR_TOKEN }}
